    - name: Install packages for local LLM
      ansible.builtin.pacman:
        name:
          - ollama
        state: present
      become: true

    - name: Install nvidia packages for local LLM
      ansible.builtin.pacman:
        name:
          - ollama-cuda # TODO: add AMD variant
        state: present
      become: true
      when: nvidia_check.rc == 0

    # TODO: make faster by parallelizing
    - name: Enable and start systemd services
      ansible.builtin.systemd_service:
        unit: '{{ item }}.service'
        enabled: yes
        state: started
      with_items:
        - ollama
      become: true

    # TODO: refactor
    - name: Configure Ollama environment variables
      ansible.builtin.copy:
        dest: /etc/systemd/system/ollama.service.d/override.conf
        content: |
          [Service]
          Environment="OLLAMA_CONTEXT_LENGTH=64000"
        owner: root
        group: root
        mode: "644"
      become: true
      # notify: restart ollama # TODO: do we need restarts?

    - name: Check which AUR packages are already installed
      vars:
        aur_packages:
          - llmfit
      ansible.builtin.command:
        cmd: "pacman -Qi {{ item }}"
      loop: "{{ aur_packages }}"
      register: aur_check
      failed_when: false
      changed_when: false

    - name: Install missing AUR packages manually
      vars:
        missing_packages: "{{ aur_check.results | rejectattr('rc', 'eq', 0) | map(attribute='item') | list }}"
      ansible.builtin.shell: |
        runuser -u aur_builder -- yay -S --aur --noconfirm --noprogressbar --needed {{ missing_packages | join(' ') }}
      args:
        executable: /bin/bash
      when: missing_packages | length > 0
      become: true
