---
- hosts: "{{ target_hosts }}"
  tasks:
    - name: Set ansible_user variable # TODO: fix https://github.com/ansible/ansible/issues/23530
      set_fact: ansible_user="{{ lookup('pipe', 'whoami') }}"
      tags: base

    - name: Base configuration
      ansible.builtin.import_role:
        name: base
      tags: base

    - name: Configure GUI for system
      ansible.builtin.import_role:
        name: gui
      tags:
        - gui
        - never

    - name: VivoBook specific fixes/features
      ansible.builtin.import_role:
        name: vivobook-laptop
      when: "'vivobook' in ansible_product_name | lower"
      tags: machine-specific

    - name: Check if non-public configs exists
      ansible.builtin.stat:
        path: ../private-rice
      register: private_rice_dir
      tags: private

    - name: Apply local non-public configuration
      ansible.builtin.include_role: # TODO: fix include_role instead of import_role as a workaround for not being able tp properly use when
        name: ../private-rice/roles/private
      when: private_rice_dir.stat.exists
      tags: private

    - name: Add VM emulator
      ansible.builtin.import_role:
        name: vm
      tags:
        - vm-emulation
        - never

    - name: Install games
      ansible.builtin.import_role:
        name: games
      tags:
        - games
        - never

    - name: Prepare local LLm infrastructure
      ansible.builtin.import_role:
        name: local-llm
      tags:
        - local-llm
        - never
