---
- hosts: localhost
  tasks:
    - name: Enable sudo for wheel group
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        regexp: '^# %wheel ALL=\(ALL:ALL\) ALL'
        line: "%wheel ALL=(ALL:ALL) ALL"
        state: present
        validate: "visudo -cf %s"
      become: true

    - name: Restricting root login
      ansible.builtin.user:
        name: root
        password: "!"
      become: true

    - name: Set hostname
      ansible.builtin.hostname:
        name: "{{ hostname }}"

    - name: Copy .zshrc
      ansible.builtin.copy:
        src: ".zshrc"
        dest: "/home/{{ username }}/.zshrc"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: "0644"

    - name: Copy .local
      ansible.builtin.copy:
        src: ".local"
        dest: "/home/{{ username }}/"
        owner: "{{ username }}"
        group: "{{ username }}"
        directory_mode: "0755"
        mode: "0644"

    - name: Copy .config
      ansible.builtin.copy:
        src: ".config"
        dest: "/home/{{ username }}/"
        owner: "{{ username }}"
        group: "{{ username }}"
        directory_mode: "0755"
        mode: "0644"

    - name: Install packages
      ansible.builtin.pacman:
        name:
          # - uv # should be beforehand
          # - git # should be beforehand
          - zsh
          - alacritty
          - sway
          - qutebrowser
          - qt6-base # for qutebrowser TODO: check if actually needed
          - qt6-webengine # for qutebrowser TODO: check if actually needed
          - qt6-wayland # for qutebrowser TODO: check if actually needed
          - mesa # for qutebrowser TODO: check if actually needed
          - xcb-util-cursor # for qutebrowser TODO: check if actually needed
          - flatpak
          - ffmpeg # for video/audio processing
          - pipewire # for audio handling
          - wireplumber # pipewire helper
          - pipewire-pulse # pipewire helper - pulseaudio replacement
          - man-db # main man repo
          - man-pages # provides both the Linux and the POSIX.1 man pages
          - openssh # ssh/scp/sftp
          - curl
          - nvm # TODO: needs to be added to .zshrc
          - docker
          - docker-compose
          - lazydocker
          # - pass # password manager TODO: configure and test
          # - mc/vifm # possible file manager
          # - upower/powertop/auto-cpufreq/tlp # possible eco power/resource management
        state: present
      become: true

    - name: Enable and start docker.service
      ansible.builtin.systemd:
        name: docker.service
        enabled: yes
        state: started

    - name: Ensure user is in docker group
      ansible.builtin.user:
        name: "{{ username }}"
        groups: docker
        append: yes

    # re login !!!

    - name: Set default shell to zsh
      ansible.builtin.user:
        name: "{{ username }}"
        shell: /usr/bin/zsh
      become: true

    - name: Configure git username
      community.general.git_config:
        name: user.name
        value: "{{ git_user_name }}"
        scope: global

    # - name: Configure git email # TODO: refactor to apply for all ~/projects and ~/jobs
    #   community.general.git_config:
    #     name: user.email
    #     value: "{{ git_user_email }}"
    #     scope: local
    #     repo: ./ # TODO: ~/projects/rice - make sure run from repo root

    - name: Install flatpak packages
      community.general.flatpak:
        name:
          - io.github.ungoogled_software.ungoogled_chromium
          - me.iepure.devtoolbox
