    - name: Enable multilib repository
      ansible.builtin.replace:
        path: /etc/pacman.conf
        regexp: '^#\[multilib\]\n#Include = /etc/pacman.d/mirrorlist'
        replace: "[multilib]\nInclude = /etc/pacman.d/mirrorlist"
      become: true

    - name: Install packages
      ansible.builtin.pacman:
        name:
          - lib32-nvidia-utils # drivers for stream # TODO: add check for actual GPUs vendors
          - lib32-vulkan-intel # drivers for stream # TODO: add check for actual GPUs vendors
          - steam
          - dwarffortress
          - prismlauncher
          - scanmem # locate and modify variables in an executing process
        state: present
      become: true

    - name: Check which AUR packages are already installed
      vars:
        aur_packages:
          - nsnake
      ansible.builtin.command:
        cmd: "pacman -Qi {{ item }}"
      loop: "{{ aur_packages }}"
      register: aur_check
      failed_when: false
      changed_when: false

    - name: Install missing AUR packages manually
      vars:
        missing_packages: "{{ aur_check.results | rejectattr('rc', 'eq', 0) | map(attribute='item') | list }}"
      ansible.builtin.shell: |
        runuser -u aur_builder -- yay -S --aur --noconfirm --noprogressbar --needed {{ missing_packages | join(' ') }}
      args:
        executable: /bin/bash
      when: missing_packages | length > 0
      become: true
