    - name: Install packages
      ansible.builtin.pacman:
        name:
          - qutebrowser
          - xcb-util-cursor # for qutebrowser TODO: check if actually needed
          - mesa # for qutebrowser TODO: check if actually needed
          - qt6-base # for qutebrowser TODO: check if actually needed
          - qt6-webengine # for qutebrowser TODO: check if actually needed
          - qt6-wayland # for qutebrowser TODO: check if actually needed
        state: present
      become: true

    - name: Check if qutebrowser is already the default browser
      ansible.builtin.shell: xdg-mime query default x-scheme-handler/http
      register: current_default_browser
      changed_when: false

    - name: Set qutebrowser as default web browser
      ansible.builtin.shell: xdg-settings set default-web-browser org.qutebrowser.qutebrowser.desktop
      when: "'org.qutebrowser.qutebrowser.desktop' not in current_default_browser.stdout"
      changed_when: true

    - name: Set qutebrowser as default for http and https
      ansible.builtin.shell: xdg-mime default org.qutebrowser.qutebrowser.desktop x-scheme-handler/http x-scheme-handler/https
      when: "'org.qutebrowser.qutebrowser.desktop' not in current_default_browser.stdout"
      changed_when: true

    # TODO: stop upgrading!
    - name: Add DRM support to qutebrowser
      vars:
        aur_packages:
          - chromium-widevine # for qutebrowser, allows streaming (DRM content)
      ansible.builtin.shell: |
        runuser -u aur_builder -- yay -S --noconfirm --noprogressbar --needed {{ aur_packages | join(' ') }}
      args:
        executable: /bin/bash
      register: aur_install_result
      changed_when: "'Downloading' in aur_install_result.stdout"
      become: true

    - name: Add backup browser
      community.general.flatpak:
        name:
          - io.github.ungoogled_software.ungoogled_chromium
