    - name: Install packages
      ansible.builtin.pacman:
        name:
          - qutebrowser
          - xcb-util-cursor # for qutebrowser TODO: check if actually needed
          - mesa # for qutebrowser TODO: check if actually needed
          - qt6-base # for qutebrowser TODO: check if actually needed
          - qt6-webengine # for qutebrowser TODO: check if actually needed
          - qt6-wayland # for qutebrowser TODO: check if actually needed
        state: present
      become: true

    - name: Check if qutebrowser is already the default browser
      ansible.builtin.shell: xdg-mime query default x-scheme-handler/http
      register: current_default_browser
      changed_when: false

    - name: Set qutebrowser as default web browser
      ansible.builtin.shell: xdg-settings set default-web-browser org.qutebrowser.qutebrowser.desktop
      when: "'org.qutebrowser.qutebrowser.desktop' not in current_default_browser.stdout"
      changed_when: true

    - name: Set qutebrowser as default for http and https
      ansible.builtin.shell: xdg-mime default org.qutebrowser.qutebrowser.desktop x-scheme-handler/http x-scheme-handler/https
      when: "'org.qutebrowser.qutebrowser.desktop' not in current_default_browser.stdout"
      changed_when: true

    - name: Check which AUR packages are already installed
      vars:
        aur_packages:
          - chromium-widevine
      ansible.builtin.command:
        cmd: "pacman -Qi {{ item }}"
      loop: "{{ aur_packages }}"
      register: aur_check
      failed_when: false
      changed_when: false

    - name: Install missing AUR packages manually
      vars:
        missing_packages: "{{ aur_check.results | rejectattr('rc', 'eq', 0) | map(attribute='item') | list }}"
      ansible.builtin.shell: |
        runuser -u aur_builder -- yay -S --aur --noconfirm --noprogressbar --needed {{ missing_packages | join(' ') }}
      args:
        executable: /bin/bash
      when: missing_packages | length > 0
      become: true

    - name: Add backup browser
      community.general.flatpak:
        name:
          - io.github.ungoogled_software.ungoogled_chromium
