---
- hosts: localhost
  tasks:
    - name: Enable sudo for wheel group (password required)
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        regexp: '^# %wheel ALL=\(ALL:ALL\) ALL'
        line: '%wheel ALL=(ALL:ALL) ALL'
        state: present
        validate: 'visudo -cf %s'
      become: true

    - name: Enable sudo for wheel group without password
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        regexp: '^# %wheel ALL=\(ALL:ALL\) NOPASSWD: ALL'
        line: '%wheel ALL=(ALL:ALL) NOPASSWD: ALL'
        state: present
        validate: 'visudo -cf %s'
      become: true

    - name: Set hostname
      ansible.builtin.hostname:
        name: ecm

    # Copy .zshrc from Projects/rice
    # Set default shell to zsh

    - name: Install packages
      ansible.builtin.pacman:
        name:
          - git
          - zsh
          - alacritty
          # - sway
        state: present
      become: true
