    - name: Enable sudo for wheel group
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        regexp: '^# %wheel ALL=\(ALL:ALL\) ALL'
        line: "%wheel ALL=(ALL:ALL) ALL"
        state: present
        validate: "visudo -cf %s"
      become: true

    - name: Restricting root login
      ansible.builtin.user:
        name: root
        password: "!"
      become: true

    - name: Set timezone
      community.general.timezone:
        name: Europe/Kyiv
      become: true
