    - name: Enable sudo for wheel group
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        regexp: '^# %wheel ALL=\(ALL:ALL\) ALL'
        line: "%wheel ALL=(ALL:ALL) ALL"
        state: present
        validate: "visudo -cf %s"
      become: true

    - name: Restricting root login
      ansible.builtin.user:
        name: root
        password: "!"
      become: true

    - name: Set timezone
      community.general.timezone:
        name: Europe/Kyiv
      become: true

    # TODO: make faster by using ansible.posix.synchronize (bad, requires rsync) or by parallelizing
    - name: Copy dotfiles
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "/home/{{ ansible_user }}/"
        mode: preserve
      with_items:
        - .zshrc
        - .zshenv
        - .zprofile
        - .config
        - .local

    - name: Install packages
      ansible.builtin.pacman:
        name:
        # system maintainability
          - pacman-contrib # paccache
        # base system standards
          - xdg-user-dirs # "well known" (.config/user-dirs.dirs) user directories manager
          - zsh
          - upower
          - tlp
          - tlp-pd
        # base system senses
          - pipewire # for audio handling
          - wireplumber # pipewire helper
          - pipewire-pulse # pipewire helper - pulseaudio replacement
          - brightnessctl # backlight/screen brightness manager
          - openssh # ssh/scp/sftp
          - bluez # bluetooth
          - bluez-utils # bluez cli
          - bluetui # bluetooth tui
          # - openvpn # maybe needed - TODO - test
          - networkmanager-openvpn # NetworkManager restart needed
        # base utils
          - man-db # main man repo
          - man-pages # provides both the Linux and the POSIX.1 man pages
          - pass # password manager
          - emacs-nox
          - mc # file manager # TODO: check ranger
          - bc # calculator
          - curl
          - htop
          - ncdu # disk usage display
          - mpv # TODO: merge with vlc
          - ffmpeg # for video/audio processing
          - tree
          - jq
          - yq
          - croc # super convinient file node-to-node transfer tool
          - zbar # qr/bar codes reader (cli/webcam)
          - qrencode
        # base development tools
          - plantuml
          - hurl # curl automation
          - fnm
          - docker
          - docker-compose
          - pastel # color palets
          - speedtest-cli # https://speed.cloudflare.com could be used in browser
          - fastfetch # system info
          - asciinema # terminal session recording
        state: present
      become: true

    # TODO: make faster by parallelizing
    - name: Enable and start systemd services
      ansible.builtin.systemd:
        unit: '{{ item }}.service'
        enabled: yes
        state: started
      with_items:
        - bluetooth
        - tlp
        - tlp-pd
        - docker
      become: true

    - name: Ensure user is respective groups
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
      become: true

    - name: Create XDG user directories
      ansible.builtin.file:
        path: "/home/{{ ansible_user }}/{{ item }}"
        state: directory
      with_items:
        - downloads

    - name: Set default shell to zsh
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        shell: /usr/bin/zsh
      become: true

    - name: Configure git init.defaultBranch
      community.general.git_config:
        name: init.defaultBranch
        value: main
        scope: global

    - name: Install and configure ly display manager (semi-login manager)
      ansible.builtin.import_tasks: ly.yml
    
    - name: Install AUR user repositories package manager
      ansible.builtin.import_tasks: aur.yml

    - name: Configure swap
      ansible.builtin.import_tasks: swap.yml
