    # TODO: make faster by using ansible.posix.synchronize (bad, requires rsync) or by parallelizing
    - name: Copy dotfiles
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "/home/{{ ansible_user }}/"
        mode: preserve
      with_items:
        - .config
        - .local

    - name: Install packages
      ansible.builtin.pacman:
        name:
        # system maintainability
          - pacman-contrib # paccache, pacdiff
        # base system standards
          - upower
          - tlp
          - tlp-pd
        # base system senses
          - pipewire # for audio handling
          - wireplumber # pipewire helper
          - pipewire-pulse # pipewire helper - pulseaudio replacement
          - brightnessctl # backlight/screen brightness manager
          - openssh # ssh/scp/sftp
          - bluez # bluetooth
          - bluez-utils # bluez cli
          - bluetui # bluetooth tui
          # - openvpn # maybe needed - TODO - test
          - networkmanager-openvpn # NetworkManager restart needed
        # base utils
          - man-db # main man repo
          - man-pages # provides both the Linux and the POSIX.1 man pages
          - pass # password manager
          - emacs-nox
          - mc # file manager # TODO: check ranger
          - bc # calculator
          - curl
          - htop
          - ncdu # disk usage display
          - mpv # TODO: merge with vlc
          - ffmpeg # for video/audio processing
          - tree
          - jq
          - yq
          - croc # super convinient file node-to-node transfer tool
          - zbar # qr/bar codes reader (cli/webcam)
          - qrencode
          # - unzip # .zip files unarchive
        # base development tools
          - plantuml
          - hurl # curl automation
          - fnm
          - docker
          - docker-compose
          - pastel # color palets
          - speedtest-cli # https://speed.cloudflare.com could be used in browser
          # - bind # network diagnostics (dig)
          # - traceroute # network diagnostics
          - fastfetch # system info
          - asciinema # terminal session recording
          # - mariadb-clients # open-sourced MySQL client
          # - valkey # open-sourced Redis
          # - aws-cli-v2
          # - terraform
        state: present
      become: true

    # TODO: make faster by parallelizing
    - name: Enable and start systemd services
      ansible.builtin.systemd_service:
        unit: '{{ item }}.service'
        enabled: yes
        state: started
      with_items:
        - bluetooth
        - tlp
        - tlp-pd
        - docker
      become: true

    - name: Ensure user is respective groups
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
      become: true
    
    - name: Install AUR user repositories package manager
      ansible.builtin.import_tasks: aur.yml

    - name: Configure swap
      ansible.builtin.import_tasks: swap.yml

    - name: Check which AUR packages are already installed
      vars:
        aur_packages:
          - opencode-bin
          - models-bin
          - pi-coding-agent
          # - argos-translate
      ansible.builtin.command:
        cmd: "pacman -Qi {{ item }}"
      loop: "{{ aur_packages }}"
      register: aur_check
      failed_when: false
      changed_when: false

    - name: Install missing AUR packages manually
      vars:
        missing_packages: "{{ aur_check.results | rejectattr('rc', 'eq', 0) | map(attribute='item') | list }}"
      ansible.builtin.shell: |
        runuser -u aur_builder -- yay -S --aur --noconfirm --noprogressbar --needed {{ missing_packages | join(' ') }}
      args:
        executable: /bin/bash
      when: missing_packages | length > 0
      become: true

    # - name: Set pinentry-curses for gnupg
    #   ansible.builtin.lineinfile:
    #     path: "/home/{{ ansible_user }}/.local/share/gnupg/gpg-agent.conf"
    #     line: 'pinentry-program /usr/bin/pinentry-curses # TODO: hide password length'
    #     create: true
    #     mode: '0600'
