    - name: Install zsh
      ansible.builtin.pacman:
        name: zsh
        state: present
      become: true

    - name: Copy .zshrc
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "/home/{{ ansible_user }}/"
        mode: preserve
      with_items:
        - .zshrc

    - name: Copy .zshenv
      ansible.builtin.blockinfile:
        block: "{{ lookup('ansible.builtin.file', '.zshenv') }}"
        path: "/home/{{ ansible_user }}/.zshenv"
        marker: "# {mark} ANSIBLE MANAGED BLOCK (base role)"
        create: true
        append_newline: true
        prepend_newline: true

    - name: Set default shell to zsh
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        shell: /usr/bin/zsh
      become: true
